{% set version = "0.8.6" %}

package:
  name: r-bold
  version: {{ version }}

source:
  fn: bold_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bold_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bold/bold_{{ version }}.tar.gz
  sha256: c697a2af76c0466c0814f328c38de203322b06cec332b437631e046e9f51015e

build:
  noarch: generic
  number: 1000
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-crul >=0.3.8
    - r-data.table
    - r-jsonlite
    - r-plyr
    - r-reshape
    - r-stringr
    - r-tibble
    - r-xml2
  run:
    - r-base
    - r-crul >=0.3.8
    - r-data.table
    - r-jsonlite
    - r-plyr
    - r-reshape
    - r-stringr
    - r-tibble
    - r-xml2

test:
  commands:
    - $R -e "library('bold')"  # [not win]
    - "\"%R%\" -e \"library('bold')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/bold
  license: MIT
  license_file: LICENSE
  summary: A programmatic interface to the Web Service methods provided by Bold Systems (<http

extra:
  recipe-maintainers:
    - dpryan79
    - ocefpaf
